version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: DB_Academy360
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Monday@01
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn pr_academy360.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:Monday@01@db:5432/DB_Academy360
