version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: DB_Academy360
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ov3E79fqnN0AtV20r0DIALYM2XvwwGYwWqdj5iIrYhJ5c6Kgi3mdzDK5Sp2qDvIP
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn pr_academy360.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - vkwokco40oo004skkgo8w0w8  # Use the service name 'db' here, not the container ID
    environment:
      DATABASE_URL: postgres://postgres:ov3E79fqnN0AtV20r0DIALYM2XvwwGYwWqdj5iIrYhJ5c6Kgi3mdzDK5Sp2qDvIP@vkwokco40oo004skkgo8w0w8:5432/DB_Academy360  # Ensure 'db' is used here
      ALLOWED_HOSTS: "*"
      DEBUG: "1"  # Enable this for development; remove for production

volumes:
  postgres_data: